apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: pred-dev
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: pred-api
          image: ghcr.io/werockstar/go-app:b4a540bbbe7a022552287a026f6c2e5e43c251fa
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.5"
              memory: 256Mi
