name: CI and CD

on:
    push:
        branches: [ main ]

jobs:
    sonarqube:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   name: SonarQube Scan
                uses: sonarsource/sonarqube-scan-action@master
                env:
                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                    SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
                with:
                    projectBaseDir: .
                    args: >
                        -Dsonar.go.coverage.reportPaths=coverage.out
                        -Dsonar.language=go
    build-and-push-docker-image:
        name: Build docker image and push to repositories
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   name: Setup SHA
                run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

            -   name: Login ghcr.io
                uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
                with:
                    registry: ghcr.io
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and push Docker image
                uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
                with:
                    push: ${{ github.ref == 'refs/heads/main' }}
                    tags: ghcr.io/${{ github.repository }}:${{ env.GITHUB_SHA }}

            -   name: Image digest
                run: echo ${{ steps.docker_build.outputs.digest }}
    gitops-versioning:
        runs-on: ubuntu-latest
        needs: build-and-push-docker-image
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   name: config git
                run: |
                    git --version
                    git config user.name "robot"
                    git config user.email "robot@werockstar.dev"
            -   name: change image tag
                run: |
                    sed -i -E "s/ghcr.io\/werockstar\/go-gitops.*$/ghcr.io\/werockstar\/go-gitops:${GITHUB_SHA}/" gitops/prep/deployment.yml
                    git add gitops/prep/deployment.yml
                    git commit -m "[skip actions] 🤖 change docker image version to ${GITHUB_SHA}"
            -   name: push changes
                uses: ad-m/github-push-action@master
                with:
                    branch: main
